
import React from "react";
import { Breadcrumb, BreadcrumbItem, BreadcrumbLink, BreadcrumbList, BreadcrumbPage, BreadcrumbSeparator } from "@/components/ui/breadcrumb";
import { Alert, AlertDescription, AlertTitle } from "@/components/ui/alert";
import { Info } from "lucide-react";
import Navbar from "@/components/layout/Navbar";
import Footer from "@/components/layout/Footer";

const Disclaimer = () => {
  return (
    <div className="flex flex-col min-h-screen">
      <Navbar />
      <main className="flex-1 pt-8 pb-16">
        <div className="container px-4 md:px-6">
          <Breadcrumb className="mb-6">
            <BreadcrumbList>
              <BreadcrumbItem>
                <BreadcrumbLink href="/">Home</BreadcrumbLink>
              </BreadcrumbItem>
              <BreadcrumbSeparator />
              <BreadcrumbItem>
                <BreadcrumbPage>Disclaimer</BreadcrumbPage>
              </BreadcrumbItem>
            </BreadcrumbList>
          </Breadcrumb>

          <div className="prose prose-blue dark:prose-invert mx-auto max-w-3xl">
            <h1 className="text-3xl font-bold mb-6">Disclaimer</h1>
            
            <Alert className="mb-8">
              <Info className="h-4 w-4" />
              <AlertTitle>Last Updated</AlertTitle>
              <AlertDescription>May 20, 2025</AlertDescription>
            </Alert>
            
            <div className="space-y-6 text-muted-foreground">
              <section>
                <h2 className="text-xl font-semibold text-foreground mb-3">1. Introduction</h2>
                <p>
                  The information provided on chartergenie.com (the "Service") is for general informational purposes only. 
                  All information on the Service is provided in good faith, however, we make no representation or 
                  warranty of any kind, express or implied, regarding the accuracy, adequacy, validity, reliability, 
                  availability, or completeness of any information on the Service.
                </p>
              </section>
              
              <section>
                <h2 className="text-xl font-semibold text-foreground mb-3">2. Not Legal Advice</h2>
                <p>
                  CharterGenie is not a law firm, and the information and documents provided through our Service do 
                  not constitute legal advice. The legal documents generated by our Service are templates based on 
                  the information you provide and should be reviewed by a qualified legal professional before use.
                </p>
                <p>
                  NO ATTORNEY-CLIENT RELATIONSHIP IS CREATED THROUGH THE USE OF OUR SERVICE.
                </p>
                <p>
                  The legal information provided on this website is not a substitute for legal advice from a qualified 
                  attorney licensed to practice in your jurisdiction. We strongly recommend consulting with a legal 
                  professional for advice concerning your specific situation.
                </p>
              </section>
              
              <section>
                <h2 className="text-xl font-semibold text-foreground mb-3">3. No Guarantee of Compliance</h2>
                <p>
                  While we strive to ensure that the legal document templates provided through our Service comply 
                  with applicable laws and regulations, we cannot guarantee that they are suitable for your specific 
                  needs or that they comply with all applicable laws in your jurisdiction.
                </p>
                <p>
                  Laws and regulations change frequently and their application can vary widely based on specific 
                  circumstances. It is your responsibility to ensure that your use of our Service and the resulting 
                  documents comply with all applicable laws and regulations.
                </p>
              </section>
              
              <section>
                <h2 className="text-xl font-semibold text-foreground mb-3">4. No Liability</h2>
                <p>
                  UNDER NO CIRCUMSTANCES SHALL CHARTERGENIE BE LIABLE FOR ANY DIRECT, INDIRECT, SPECIAL, INCIDENTAL, 
                  OR CONSEQUENTIAL DAMAGES ARISING OUT OF OR IN ANY WAY CONNECTED WITH THE USE OF OUR SERVICE, DOCUMENTS 
                  GENERATED, OR INFORMATION PROVIDED, EVEN IF CHARTERGENIE HAS BEEN ADVISED OF THE POSSIBILITY OF 
                  SUCH DAMAGES.
                </p>
              </section>
              
              <section>
                <h2 className="text-xl font-semibold text-foreground mb-3">5. External Links</h2>
                <p>
                  Our Service may contain links to external websites that are not provided or maintained by or in 
                  any way affiliated with CharterGenie. Please note that we do not guarantee the accuracy, relevance, 
                  timeliness, or completeness of any information on these external websites.
                </p>
              </section>
              
              <section>
                <h2 className="text-xl font-semibold text-foreground mb-3">6. Errors and Omissions</h2>
                <p>
                  Our Service may contain technical, typographical, or photographic errors. CharterGenie does not 
                  warrant that any of the materials on its Service are accurate, complete, or current. CharterGenie 
                  may make changes to the materials contained on its Service at any time without notice.
                </p>
              </section>
              
              <section>
                <h2 className="text-xl font-semibold text-foreground mb-3">7. Modifications</h2>
                <p>
                  CharterGenie may revise this disclaimer at any time without notice. By using this Service, 
                  you are agreeing to be bound by the current version of this disclaimer.
                </p>
              </section>
              
              <section>
                <h2 className="text-xl font-semibold text-foreground mb-3">8. Applicable Law</h2>
                <p>
                  This disclaimer shall be governed by and construed in accordance with the laws of the State of 
                  California, without regard to its conflict of law provisions.
                </p>
              </section>
              
              <section>
                <h2 className="text-xl font-semibold text-foreground mb-3">9. Contact Us</h2>
                <p>
                  If you have any questions about this disclaimer, please contact us at:
                </p>
                <p className="mt-3">
                  Email: legal@chartergenie.com<br />
                  Address: 123 Tech Drive, Suite 500, San Francisco, CA 94107
                </p>
              </section>
            </div>
          </div>
        </div>
      </main>
      <Footer />
    </div>
  );
};

export default Disclaimer;
