// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gghstvkytxzobvdeslpt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdnaHN0dmt5dHh6b2J2ZGVzbHB0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc4NTY4MzAsImV4cCI6MjA2MzQzMjgzMH0.jEl8SRzCz991ozxgLYzvQkUe_eD94BRprR07Ry5r6As";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);